---
title: "STAT-331-Final-Project"
date: now
author: "Mia Sahagian, Suhani Kashyap, Hanna Karam"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  echo: true
  message: false
  warning: false
---

# PULL commit PUSH

# Mystery Concert

**Background**: A mystery music artist is organizing a concert at Cal Poly. The biggest celebrities in the world are dropping hints on social media about who is behind it. As a music fanatic journalist at Mustang News, you need to follow the hints across Spotify, Apple Music, and global information to discover the mystery artist and let the students at Cal Poly know who’s performing.

### Import Data

```{r}

global_music <- read.csv("./Global Music Artists.csv")

apple_music <- read.csv("./apple_music_dataset.csv")

spotify_music <- read.csv("./high_popularity_spotify_data.csv")

#Find more info on the data here: 
# Apple data: https://www.kaggle.com/datasets/kanchana1990/apple-music-dataset-10000-tracks-uncovered
# Spotify data: https://www.kaggle.com/datasets/solomonameh/spotify-music-dataset?resource=download
# Global data: https://www.kaggle.com/datasets/harshdprajapati/worldwide-music-artists-dataset-with-image
```

### Data Cleaning

### Ideas

Pick: Night Changes - OneDirection

Lubridate time zone to figure out they're from the UK (ex it's this time for the artist)

Fix the track_name/merge/get ride of playlist info

Don't join apply music country

1\) Data cleaning stuff (which rows to save/not save)(how many rows and cols)

2\) Clues

3\) GGPlot most popular genre, factor reorder by genre (Pop)

4\) Energy level: medium high danceability (.672) and medium energy (0.52) leaked by justin bieber

6\) song duration

5\) data joins

6\) Country of origin/when track came out/release date - with lubridate
